language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "hhvm"

# Allow to use container infrastructure
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then composer require --no-update doctrine/mongodb-odm v1.0.0-beta12@dev; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then composer require --no-update doctrine/mongodb-odm-bundle v3.0.0-BETA6@dev; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then composer update --prefer-dist --no-interaction; else composer update --prefer-dist --no-interaction --no-scripts; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./app/console oro:requirejs:generate-config; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./app/console assets:install; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then npm install -g grunt-cli; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then npm install; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer; fi;'

script:
    - ./bin/phpunit -c app/phpunit.travis.xml --testsuite PIM_Unit_Test
    - ./phpspec-fix
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then php php-cs-fixer fix --dry-run -v --diff --config-file=.php_cs.php; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then grunt travis; fi;'

notifications:
  slack: akeneo:fDZaQeRRj1gVtXCW3f2kQAxo
